### ISSUE TITLE
Attempting to get this working

### ISSUE THREAD

**Issue by zzager** [mattdbridges/minty#2]
When running minty login --help I get:

[user@machine minty]$ minty login --help
/home/user/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/pstore.rb:315:in `transaction': undefined method`locked?' for nil:NilClass (NoMethodError)
    from /home/user/prog/minty/lib/minty/credentials.rb:56:in `save'
    from /home/user/prog/minty/lib/minty/credentials.rb:14:in`rescue in load'
    from /home/user/prog/minty/lib/minty/credentials.rb:11:in `load'
    from /home/user/prog/minty/lib/minty/cli/command.rb:11:in`initialize'
    from /home/user/prog/minty/bin/minty:9:in `new'
    from /home/user/prog/minty/bin/minty:9:in`<top (required)>'
    from /home/user/.rvm/gems/ruby-1.9.3-p448/bin/minty:23:in `load'
    from /home/user/.rvm/gems/ruby-1.9.3-p448/bin/minty:23:in`<main>'
    from /home/user/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `eval'
    from /home/user/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in`<main>'

Is there a place I'm suppose to put my login information?

Thanks.

**Comment by TvL2386** [comment]
I had this same problem with ruby-1.9.3 on my own application (ruby-2.1.0 works fine). 
The problem is that YAML::Store will not call the PStore initialize method if you don't throw a String into YAML::Store.new.
In this case (https://github.com/mattdbridges/minty/blob/master/lib/minty/credentials.rb#L55) a Pathname object is given which causes YAML::Store not to initialize the backend (PStore).

Therefor the required Mutex \@lock in the PStore code is nil.

Change https://github.com/mattdbridges/minty/blob/master/lib/minty/credentials.rb#L55 to:
      store = YAML::Store.new self.class.file.to_s

I know this is old, but google brought me here and I hope this helps people that will get here in the future.
